export const MOCK_TOP_SELLERS = [
  {
    "id": "EMP-1",
    "name": "Luuk Meijer",
    "store": "Groningen",
    "totalRevenue": 240450,
    "salesCount": 194,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 116,
    "tvMargin": 25520,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 32,
    "bbqMarginPct": 31,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 2986,
    "recentSales": []
  },
  {
    "id": "EMP-2",
    "name": "Anne Peters",
    "store": "Duiven",
    "totalRevenue": 229950,
    "salesCount": 186,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 111,
    "tvMargin": 28416,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 24,
    "bbqMarginPct": 23,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 2857,
    "recentSales": []
  },
  {
    "id": "EMP-3",
    "name": "Lotte van Dijk",
    "store": "Naarden",
    "totalRevenue": 217500,
    "salesCount": 176,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 105,
    "tvMargin": 22260,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 20,
    "bbqMarginPct": 27,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 2703,
    "recentSales": []
  },
  {
    "id": "EMP-4",
    "name": "Daan Smit",
    "store": "Rotterdam",
    "totalRevenue": 211650,
    "salesCount": 170,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 102,
    "tvMargin": 28254,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 18,
    "bbqMarginPct": 31,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 2626,
    "recentSales": []
  },
  {
    "id": "EMP-5",
    "name": "Tim de Vries",
    "store": "Naarden",
    "totalRevenue": 203100,
    "salesCount": 164,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 98,
    "tvMargin": 19012,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 30,
    "bbqMarginPct": 26,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 2523,
    "recentSales": []
  },
  {
    "id": "EMP-6",
    "name": "Johan de Groot",
    "store": "Groningen",
    "totalRevenue": 146600,
    "salesCount": 119,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 71,
    "tvMargin": 20093,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 31,
    "bbqMarginPct": 23,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1822,
    "recentSales": []
  },
  {
    "id": "EMP-7",
    "name": "Thijs Bos",
    "store": "Eindhoven",
    "totalRevenue": 146600,
    "salesCount": 119,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 71,
    "tvMargin": 19028,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 27,
    "bbqMarginPct": 21,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1822,
    "recentSales": []
  },
  {
    "id": "EMP-8",
    "name": "Mark Dijkstra",
    "store": "Alkmaar",
    "totalRevenue": 146600,
    "salesCount": 119,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 71,
    "tvMargin": 17395,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 21,
    "bbqMarginPct": 26,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1822,
    "recentSales": []
  },
  {
    "id": "EMP-9",
    "name": "Dennis Kuipers",
    "store": "Cruquius",
    "totalRevenue": 142700,
    "salesCount": 115,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 69,
    "tvMargin": 16491,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 34,
    "bbqMarginPct": 28,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1771,
    "recentSales": []
  },
  {
    "id": "EMP-10",
    "name": "Tom Hendriks",
    "store": "Zoeterwoude",
    "totalRevenue": 138950,
    "salesCount": 113,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 67,
    "tvMargin": 15276,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 35,
    "bbqMarginPct": 22,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1727,
    "recentSales": []
  },
  {
    "id": "EMP-11",
    "name": "Dennis Smit",
    "store": "Den Bosch",
    "totalRevenue": 138900,
    "salesCount": 112,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 67,
    "tvMargin": 21105,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 22,
    "bbqMarginPct": 29,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1725,
    "recentSales": []
  },
  {
    "id": "EMP-12",
    "name": "Martijn Vos",
    "store": "Breda",
    "totalRevenue": 137000,
    "salesCount": 111,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 66,
    "tvMargin": 14850,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 32,
    "bbqMarginPct": 23,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1702,
    "recentSales": []
  },
  {
    "id": "EMP-13",
    "name": "Tom de Vries",
    "store": "Eindhoven",
    "totalRevenue": 137000,
    "salesCount": 111,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 66,
    "tvMargin": 16170,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 20,
    "bbqMarginPct": 23,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1702,
    "recentSales": []
  },
  {
    "id": "EMP-14",
    "name": "Rik Dijkstra",
    "store": "Amsterdam",
    "totalRevenue": 137000,
    "salesCount": 111,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 66,
    "tvMargin": 22308,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 25,
    "bbqMarginPct": 31,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1702,
    "recentSales": []
  },
  {
    "id": "EMP-15",
    "name": "Peter Jonker",
    "store": "Eindhoven",
    "totalRevenue": 137000,
    "salesCount": 111,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 66,
    "tvMargin": 21120,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 35,
    "bbqMarginPct": 23,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1702,
    "recentSales": []
  },
  {
    "id": "EMP-16",
    "name": "Kevin Smit",
    "store": "Apeldoorn",
    "totalRevenue": 136950,
    "salesCount": 110,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 66,
    "tvMargin": 22902,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 25,
    "bbqMarginPct": 21,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1699,
    "recentSales": []
  },
  {
    "id": "EMP-17",
    "name": "Jesper Smit",
    "store": "Groningen",
    "totalRevenue": 134150,
    "salesCount": 109,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 65,
    "tvMargin": 13390,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 19,
    "bbqMarginPct": 22,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1667,
    "recentSales": []
  },
  {
    "id": "EMP-18",
    "name": "Jasper Jonker",
    "store": "Zoeterwoude",
    "totalRevenue": 132200,
    "salesCount": 107,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 64,
    "tvMargin": 21568,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 24,
    "bbqMarginPct": 21,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1642,
    "recentSales": []
  },
  {
    "id": "EMP-19",
    "name": "Jeroen de Boer",
    "store": "Doetinchem",
    "totalRevenue": 130250,
    "salesCount": 105,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 63,
    "tvMargin": 19971,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 27,
    "bbqMarginPct": 23,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1616,
    "recentSales": []
  },
  {
    "id": "EMP-20",
    "name": "Lotte Kramer",
    "store": "Doetinchem",
    "totalRevenue": 128400,
    "salesCount": 104,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 62,
    "tvMargin": 12276,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 36,
    "bbqMarginPct": 18,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1596,
    "recentSales": []
  },
  {
    "id": "EMP-21",
    "name": "Milan Scholten",
    "store": "Zoeterwoude",
    "totalRevenue": 124500,
    "salesCount": 100,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 60,
    "tvMargin": 10800,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 27,
    "bbqMarginPct": 31,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1545,
    "recentSales": []
  },
  {
    "id": "EMP-22",
    "name": "Martijn van Dongen",
    "store": "Zoeterwoude",
    "totalRevenue": 124500,
    "salesCount": 100,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 60,
    "tvMargin": 18540,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 28,
    "bbqMarginPct": 25,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1545,
    "recentSales": []
  },
  {
    "id": "EMP-23",
    "name": "Max de Boer",
    "store": "Breda",
    "totalRevenue": 121700,
    "salesCount": 99,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 59,
    "tvMargin": 14632,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 34,
    "bbqMarginPct": 31,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1513,
    "recentSales": []
  },
  {
    "id": "EMP-24",
    "name": "Jasper Kuipers",
    "store": "Utrecht",
    "totalRevenue": 119850,
    "salesCount": 98,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 58,
    "tvMargin": 12876,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 30,
    "bbqMarginPct": 24,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1492,
    "recentSales": []
  },
  {
    "id": "EMP-25",
    "name": "Ruben Veenstra",
    "store": "Groningen",
    "totalRevenue": 115950,
    "salesCount": 94,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 56,
    "tvMargin": 18648,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 32,
    "bbqMarginPct": 23,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1441,
    "recentSales": []
  },
  {
    "id": "EMP-26",
    "name": "Anne Vos",
    "store": "Bergen op Zoom",
    "totalRevenue": 115950,
    "salesCount": 94,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 56,
    "tvMargin": 15008,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 26,
    "bbqMarginPct": 21,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1441,
    "recentSales": []
  },
  {
    "id": "EMP-27",
    "name": "Sem Hoekstra",
    "store": "Tilburg",
    "totalRevenue": 115950,
    "salesCount": 94,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 56,
    "tvMargin": 8904,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 24,
    "bbqMarginPct": 25,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1441,
    "recentSales": []
  },
  {
    "id": "EMP-28",
    "name": "Kevin van der Berg",
    "store": "Utrecht",
    "totalRevenue": 114050,
    "salesCount": 93,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 55,
    "tvMargin": 17820,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 30,
    "bbqMarginPct": 32,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1418,
    "recentSales": []
  },
  {
    "id": "EMP-29",
    "name": "Rik Kuipers",
    "store": "Bergen op Zoom",
    "totalRevenue": 114000,
    "salesCount": 92,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 55,
    "tvMargin": 9680,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 28,
    "bbqMarginPct": 32,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1416,
    "recentSales": []
  },
  {
    "id": "EMP-30",
    "name": "Johan Smit",
    "store": "Bergen op Zoom",
    "totalRevenue": 112100,
    "salesCount": 91,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 54,
    "tvMargin": 16308,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 20,
    "bbqMarginPct": 18,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1393,
    "recentSales": []
  },
  {
    "id": "EMP-31",
    "name": "Peter Hoekstra",
    "store": "Utrecht",
    "totalRevenue": 105350,
    "salesCount": 85,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 51,
    "tvMargin": 12699,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 25,
    "bbqMarginPct": 22,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1307,
    "recentSales": []
  },
  {
    "id": "EMP-32",
    "name": "Tim Peters",
    "store": "Alkmaar",
    "totalRevenue": 101550,
    "salesCount": 82,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 49,
    "tvMargin": 8673,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 24,
    "bbqMarginPct": 30,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1261,
    "recentSales": []
  },
  {
    "id": "EMP-33",
    "name": "Kevin de Boer",
    "store": "Apeldoorn",
    "totalRevenue": 101550,
    "salesCount": 82,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 49,
    "tvMargin": 11466,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 19,
    "bbqMarginPct": 21,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1261,
    "recentSales": []
  },
  {
    "id": "EMP-34",
    "name": "Ruben Peters",
    "store": "Groningen",
    "totalRevenue": 99600,
    "salesCount": 80,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 48,
    "tvMargin": 14640,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 25,
    "bbqMarginPct": 21,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1236,
    "recentSales": []
  },
  {
    "id": "EMP-35",
    "name": "Lotte Visser",
    "store": "Zoeterwoude",
    "totalRevenue": 99600,
    "salesCount": 80,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 48,
    "tvMargin": 10368,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 34,
    "bbqMarginPct": 20,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1236,
    "recentSales": []
  },
  {
    "id": "EMP-36",
    "name": "Peter van Dijk",
    "store": "Eindhoven",
    "totalRevenue": 99600,
    "salesCount": 80,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 48,
    "tvMargin": 16464,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 27,
    "bbqMarginPct": 25,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1236,
    "recentSales": []
  },
  {
    "id": "EMP-37",
    "name": "Jasper Scholten",
    "store": "Zoeterwoude",
    "totalRevenue": 96800,
    "salesCount": 79,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 47,
    "tvMargin": 14993,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 19,
    "bbqMarginPct": 21,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1204,
    "recentSales": []
  },
  {
    "id": "EMP-38",
    "name": "Lotte Dijkstra",
    "store": "Tilburg",
    "totalRevenue": 96800,
    "salesCount": 79,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 47,
    "tvMargin": 14852,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 37,
    "bbqMarginPct": 26,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1204,
    "recentSales": []
  },
  {
    "id": "EMP-39",
    "name": "Sem Peters",
    "store": "Utrecht",
    "totalRevenue": 93000,
    "salesCount": 76,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 45,
    "tvMargin": 9360,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 34,
    "bbqMarginPct": 27,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1158,
    "recentSales": []
  },
  {
    "id": "EMP-40",
    "name": "Tim Vos",
    "store": "Doetinchem",
    "totalRevenue": 93000,
    "salesCount": 76,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 45,
    "tvMargin": 7380,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 37,
    "bbqMarginPct": 22,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1158,
    "recentSales": []
  },
  {
    "id": "EMP-41",
    "name": "Mark Hoekstra",
    "store": "Leeuwarden",
    "totalRevenue": 92900,
    "salesCount": 75,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 45,
    "tvMargin": 10890,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 36,
    "bbqMarginPct": 24,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1153,
    "recentSales": []
  },
  {
    "id": "EMP-42",
    "name": "Thijs de Vries",
    "store": "Leeuwarden",
    "totalRevenue": 92900,
    "salesCount": 75,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 45,
    "tvMargin": 7065,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 31,
    "bbqMarginPct": 21,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1153,
    "recentSales": []
  },
  {
    "id": "EMP-43",
    "name": "Lisa Kuipers",
    "store": "Utrecht",
    "totalRevenue": 92900,
    "salesCount": 75,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 45,
    "tvMargin": 13455,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 23,
    "bbqMarginPct": 32,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1153,
    "recentSales": []
  },
  {
    "id": "EMP-44",
    "name": "Maikel Timmermans",
    "store": "Duiven",
    "totalRevenue": 91050,
    "salesCount": 74,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 44,
    "tvMargin": 13508,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 37,
    "bbqMarginPct": 26,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1132,
    "recentSales": []
  },
  {
    "id": "EMP-45",
    "name": "Mark van Dijk",
    "store": "Nijmegen",
    "totalRevenue": 91050,
    "salesCount": 74,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 44,
    "tvMargin": 12144,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 37,
    "bbqMarginPct": 21,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1132,
    "recentSales": []
  },
  {
    "id": "EMP-46",
    "name": "Niels de Boer",
    "store": "Nijmegen",
    "totalRevenue": 91050,
    "salesCount": 74,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 44,
    "tvMargin": 13596,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 27,
    "bbqMarginPct": 18,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1132,
    "recentSales": []
  },
  {
    "id": "EMP-47",
    "name": "Joris Jonker",
    "store": "Leeuwarden",
    "totalRevenue": 91050,
    "salesCount": 74,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 44,
    "tvMargin": 10120,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 28,
    "bbqMarginPct": 32,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1132,
    "recentSales": []
  },
  {
    "id": "EMP-48",
    "name": "Sem Jansen",
    "store": "Zoeterwoude",
    "totalRevenue": 89150,
    "salesCount": 73,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 43,
    "tvMargin": 11524,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 28,
    "bbqMarginPct": 29,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1109,
    "recentSales": []
  },
  {
    "id": "EMP-49",
    "name": "Jasper Mulder",
    "store": "Apeldoorn",
    "totalRevenue": 87200,
    "salesCount": 71,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 42,
    "tvMargin": 11298,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 20,
    "bbqMarginPct": 18,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1084,
    "recentSales": []
  },
  {
    "id": "EMP-50",
    "name": "Dennis Bos",
    "store": "Leeuwarden",
    "totalRevenue": 87200,
    "salesCount": 71,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 42,
    "tvMargin": 11592,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 29,
    "bbqMarginPct": 20,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1084,
    "recentSales": []
  },
  {
    "id": "EMP-51",
    "name": "Martijn Peters",
    "store": "Tilburg",
    "totalRevenue": 87150,
    "salesCount": 70,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 42,
    "tvMargin": 12264,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 22,
    "bbqMarginPct": 25,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1081,
    "recentSales": []
  },
  {
    "id": "EMP-52",
    "name": "Sander de Vries",
    "store": "Breda",
    "totalRevenue": 87150,
    "salesCount": 70,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 42,
    "tvMargin": 7686,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 26,
    "bbqMarginPct": 32,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1081,
    "recentSales": []
  },
  {
    "id": "EMP-53",
    "name": "Kevin Mulder",
    "store": "Apeldoorn",
    "totalRevenue": 84350,
    "salesCount": 69,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 41,
    "tvMargin": 10578,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 26,
    "bbqMarginPct": 25,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1049,
    "recentSales": []
  },
  {
    "id": "EMP-54",
    "name": "Lisa Jonker",
    "store": "Cruquius",
    "totalRevenue": 84350,
    "salesCount": 69,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 41,
    "tvMargin": 12546,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 25,
    "bbqMarginPct": 31,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1049,
    "recentSales": []
  },
  {
    "id": "EMP-55",
    "name": "Peter Jonker",
    "store": "Apeldoorn",
    "totalRevenue": 82500,
    "salesCount": 68,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 40,
    "tvMargin": 12520,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 20,
    "bbqMarginPct": 24,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1029,
    "recentSales": []
  },
  {
    "id": "EMP-56",
    "name": "Stan van Dijk",
    "store": "Alkmaar",
    "totalRevenue": 82400,
    "salesCount": 67,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 40,
    "tvMargin": 6760,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 35,
    "bbqMarginPct": 32,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 1024,
    "recentSales": []
  },
  {
    "id": "EMP-57",
    "name": "Sem Jonker",
    "store": "Cruquius",
    "totalRevenue": 76700,
    "salesCount": 63,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 37,
    "tvMargin": 9213,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 23,
    "bbqMarginPct": 23,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 955,
    "recentSales": []
  },
  {
    "id": "EMP-58",
    "name": "Sem Bakker",
    "store": "Bergen op Zoom",
    "totalRevenue": 76700,
    "salesCount": 63,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 37,
    "tvMargin": 8547,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 31,
    "bbqMarginPct": 21,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 955,
    "recentSales": []
  },
  {
    "id": "EMP-59",
    "name": "Bas Visser",
    "store": "Nijmegen",
    "totalRevenue": 76650,
    "salesCount": 62,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 37,
    "tvMargin": 8140,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 25,
    "bbqMarginPct": 19,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 952,
    "recentSales": []
  },
  {
    "id": "EMP-60",
    "name": "Tom Bos",
    "store": "Tilburg",
    "totalRevenue": 76650,
    "salesCount": 62,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 37,
    "tvMargin": 9509,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 27,
    "bbqMarginPct": 21,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 952,
    "recentSales": []
  },
  {
    "id": "EMP-61",
    "name": "Ruben Kuipers",
    "store": "Den Bosch",
    "totalRevenue": 76650,
    "salesCount": 62,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 37,
    "tvMargin": 8917,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 19,
    "bbqMarginPct": 18,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 952,
    "recentSales": []
  },
  {
    "id": "EMP-62",
    "name": "Tim Timmermans",
    "store": "Alkmaar",
    "totalRevenue": 70050,
    "salesCount": 58,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 34,
    "tvMargin": 8228,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 18,
    "bbqMarginPct": 20,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 874,
    "recentSales": []
  },
  {
    "id": "EMP-63",
    "name": "Jeroen de Vries",
    "store": "Apeldoorn",
    "totalRevenue": 68100,
    "salesCount": 56,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 33,
    "tvMargin": 9999,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 35,
    "bbqMarginPct": 25,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 849,
    "recentSales": []
  },
  {
    "id": "EMP-64",
    "name": "Jesper Peters",
    "store": "Utrecht",
    "totalRevenue": 64250,
    "salesCount": 53,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 31,
    "tvMargin": 6107,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 23,
    "bbqMarginPct": 29,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 800,
    "recentSales": []
  },
  {
    "id": "EMP-65",
    "name": "Niels Vos",
    "store": "Utrecht",
    "totalRevenue": 55650,
    "salesCount": 46,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 27,
    "tvMargin": 8289,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 28,
    "bbqMarginPct": 28,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 694,
    "recentSales": []
  },
  {
    "id": "EMP-66",
    "name": "Bas Bakker",
    "store": "Tilburg",
    "totalRevenue": 55550,
    "salesCount": 45,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 27,
    "tvMargin": 4671,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 19,
    "bbqMarginPct": 28,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 689,
    "recentSales": []
  },
  {
    "id": "EMP-67",
    "name": "Niels Mulder",
    "store": "Rotterdam",
    "totalRevenue": 55550,
    "salesCount": 45,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 27,
    "tvMargin": 6642,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 32,
    "bbqMarginPct": 20,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 689,
    "recentSales": []
  },
  {
    "id": "EMP-68",
    "name": "Daan Visser",
    "store": "Apeldoorn",
    "totalRevenue": 55550,
    "salesCount": 45,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 27,
    "tvMargin": 7587,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 33,
    "bbqMarginPct": 32,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 689,
    "recentSales": []
  },
  {
    "id": "EMP-69",
    "name": "Sander Bakker",
    "store": "Amsterdam",
    "totalRevenue": 55550,
    "salesCount": 45,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 27,
    "tvMargin": 5184,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 21,
    "bbqMarginPct": 20,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 689,
    "recentSales": []
  },
  {
    "id": "EMP-70",
    "name": "Max Timmermans",
    "store": "Doetinchem",
    "totalRevenue": 53700,
    "salesCount": 44,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 26,
    "tvMargin": 3952,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 30,
    "bbqMarginPct": 26,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 669,
    "recentSales": []
  },
  {
    "id": "EMP-71",
    "name": "Thijs Timmermans",
    "store": "Alkmaar",
    "totalRevenue": 53700,
    "salesCount": 44,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 26,
    "tvMargin": 4784,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 37,
    "bbqMarginPct": 22,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 669,
    "recentSales": []
  },
  {
    "id": "EMP-72",
    "name": "Rik van der Berg",
    "store": "Tilburg",
    "totalRevenue": 49850,
    "salesCount": 41,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 24,
    "tvMargin": 8160,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 19,
    "bbqMarginPct": 30,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 620,
    "recentSales": []
  },
  {
    "id": "EMP-73",
    "name": "Jeroen Hendriks",
    "store": "Doetinchem",
    "totalRevenue": 49850,
    "salesCount": 41,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 24,
    "tvMargin": 3912,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 24,
    "bbqMarginPct": 21,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 620,
    "recentSales": []
  },
  {
    "id": "EMP-74",
    "name": "Tom Jonker",
    "store": "Rotterdam",
    "totalRevenue": 37400,
    "salesCount": 31,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 18,
    "tvMargin": 2790,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 24,
    "bbqMarginPct": 20,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 466,
    "recentSales": []
  },
  {
    "id": "EMP-75",
    "name": "Johan van der Berg",
    "store": "Tilburg",
    "totalRevenue": 30750,
    "salesCount": 26,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 15,
    "tvMargin": 2565,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 37,
    "bbqMarginPct": 25,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 385,
    "recentSales": []
  },
  {
    "id": "EMP-76",
    "name": "Kevin de Boer",
    "store": "Zoeterwoude",
    "totalRevenue": 28800,
    "salesCount": 24,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 14,
    "tvMargin": 4368,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 20,
    "bbqMarginPct": 20,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 360,
    "recentSales": []
  },
  {
    "id": "EMP-77",
    "name": "Lotte Dekker",
    "store": "Den Bosch",
    "totalRevenue": 28800,
    "salesCount": 24,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 14,
    "tvMargin": 3724,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 20,
    "bbqMarginPct": 26,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 360,
    "recentSales": []
  },
  {
    "id": "EMP-78",
    "name": "Sander Timmermans",
    "store": "Naarden",
    "totalRevenue": 26900,
    "salesCount": 23,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 13,
    "tvMargin": 4355,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 36,
    "bbqMarginPct": 31,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 337,
    "recentSales": []
  },
  {
    "id": "EMP-79",
    "name": "Bram Dijkstra",
    "store": "Doetinchem",
    "totalRevenue": 26850,
    "salesCount": 22,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 13,
    "tvMargin": 3081,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 28,
    "bbqMarginPct": 18,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 334,
    "recentSales": []
  },
  {
    "id": "EMP-80",
    "name": "Jeroen van Dongen",
    "store": "Amsterdam",
    "totalRevenue": 24900,
    "salesCount": 20,
    "todayRevenue": 0,
    "todaySalesCount": 0,
    "tvSold": 12,
    "tvMargin": 3276,
    "bbqSold": 0,
    "bbqMargin": 0,
    "tvMarginPct": 31,
    "bbqMarginPct": 18,
    "accessoriesSold": 0,
    "accessoriesMargin": 0,
    "points": 309,
    "recentSales": []
  }
];
